version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      - WEBUI_AUTH=false  # Set to true to enable authentication
      - WEBUI_VERSION=main  # Set to main for latest builds or a specific version
    volumes:
      - openwebui-data:/app/backend/data


volumes:
  openwebui-data:
